;;; early-init.el --- Early initialization -*- lexical-binding: t; -*-

;; Prevent package.el from loading since we use straight.el.
(setq package-enable-at-startup nil)

;; Load shell env snapshot generated by emacs-refresh-env.
;; Mirrors Doom's approach: snapshot is written once by a script running
;; `zsh -ic env`, so no subprocess is needed at startup.
(let ((env-file (expand-file-name "env" user-emacs-directory)))
  (when (file-readable-p env-file)
    (dolist (line (split-string (with-temp-buffer
                                  (insert-file-contents env-file)
                                  (buffer-string))
                                "\n" t))
      (when (string-match "^\\([^=\n]+\\)=\\(.*\\)$" line)
        (setenv (match-string 1 line) (match-string 2 line))))
    (when-let ((path (getenv "PATH")))
      (setq exec-path (append (split-string path ":") (list exec-directory))))))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
