;;; early-init.el --- Early initialization -*- lexical-binding: t; -*-

;; Prevent package.el from loading since we use straight.el.
(setq package-enable-at-startup nil)

;; Suppress UI chrome before the first frame is created so Emacs never
;; renders them — avoids a redisplay_internal hit when init.el disables them.
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(menu-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)

;; Suppress GC and file-handler regexp checks during startup; both are
;; restored to their runtime values by the emacs-startup hook in init.el.
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 1.0)
(defvar my/file-name-handler-alist file-name-handler-alist)
(setq file-name-handler-alist nil)

;; Load shell env snapshot generated by emacs-refresh-env.
;; Mirrors Doom's approach: snapshot is written once by a script running
;; `zsh -ic env`, so no subprocess is needed at startup.
(let ((env-file (expand-file-name "env" user-emacs-directory)))
  (when (file-readable-p env-file)
    (dolist (line (split-string (with-temp-buffer
                                  (insert-file-contents env-file)
                                  (buffer-string))
                                "\n" t))
      (when (string-match "^\\([^=\n]+\\)=\\(.*\\)$" line)
        (setenv (match-string 1 line) (match-string 2 line))))
    (when-let ((path (getenv "PATH")))
      (setq exec-path (append (split-string path ":") (list exec-directory))))))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
