#!/usr/bin/env zsh

AGKOZAK_COLORS_PROMPT_CHAR='magenta'
AGKOZAK_MULTILINE=0
AGKOZAK_PROMPT_CHAR=( ❯ ❯ ❮ )
AGKOZAK_USER_HOST_DISPLAY=0
AGKOZAK_CMD_EXEC_TIME_CHARS=( '[' ']' )
AGKOZAK_COLORS_BRANCH_STATUS=8
AGKOZAK_COLORS_CMD_EXEC_TIME=8
