#!/usr/bin/env zsh

if [[ "$ZPROF" = true ]]; then
        zmodload zsh/zprof
fi

source $HOME/.zsh/exports.zsh

if [ -f "$HOME/.zsh_plugins.sh" ]; then
        source $HOME/.zsh_plugins.sh
else
        echo "Bundling zsh plugins..."
        antibody bundle <$HOME/.zsh/plugins.txt >$HOME/.zsh_plugins.sh
        source $HOME/.zsh_plugins.sh
fi

source $HOME/.zsh/init.zsh
source $HOME/.zsh/evals.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/stack.zsh
source $HOME/.zsh/keys.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/gpg-agent.zsh

if [ -f "$HOME/.cargo/env" ]; then
        source $HOME/.cargo/env
fi

# load base16 themes if on terminal
if [[ -n $DISPLAY ]]; then
        # base16 theme
        base16_gruvbox-dark-hard
fi

if (($+commands[fortune])); then
        fortune
fi

if [[ "$ZPROF" = true ]]; then
        zprof
fi
