#!/usr/bin/bash

# Test if $1 is available
isavailable() {
    type "$1" &>/dev/null
}

# screen powersave
xset +dpms
xset dpms 0 0 300
xset r rate 180 40

# 230 has IPS or TN screen with 125.37 DPI
xrandr --dpi 125.37

# run xrdb
[[ -f $HOME/.Xresources ]] && xrdb -load $HOME/.Xresources

# run urxvt daemon
[[ -z "$(pidof urxvtd)" ]] && urxvtd --quiet --opendisplay --fork

# start redshift
# current lat/log: oud-zuid
isavailable redshift && redshift -l "-27.578023":"-48.537449" -t "5500":"3000" &
isavailable synclient && synclient TouchpadOff=1 &

isavailable nm-applet && nm-applet &
isavailable xautolock && xautolock -time 10 -locker ~/.bin/lock.sh &
isavailable dunst && dunst -config ~/.config/dunst/dunstrc &
isavailable xss-lock && xss-lock -- ~/.bin/lock.sh &
isavailable xcompmgr && xcompmgr -c &
isavailable rescuetime && rescuetime &
isavailable feh && feh --bg-fill --randomize ~/workspace/wallpapers/* &
isavailable unclutter && unclutter &

# Here Xfce is kept as default
session=${1:-i3}

case $session in
    i3|i3wm           ) exec i3;;
    xfce|xfce4        ) exec startxfce4;;
    dwm|dwm           ) exec dwm;;
    # No known session, try to run it as command
    *) exec $1;;
esac
