#!/usr/bin/bash

# Test if $1 is available
isavailable() {
    type "$1" &>/dev/null
}

# screen powersave
xset +dpms
xset dpms 0 0 300
xset r rate 180 40

# 230 has IPS or TN screen with 125.37 DPI
xrandr --dpi 125.37

# run xrdb
[[ -f $HOME/.Xresources ]] && xrdb -load $HOME/.Xresources

# run urxvt daemon
[[ -z "$(pidof urxvtd)" ]] && urxvtd --quiet --opendisplay --fork

# start redshift
# current lat/log: oud-zuid
isavailable redshift && redshift -l "-27.578023":"-48.537449" -t "5500":"3000" &
isavailable synclient && synclient TouchpadOff=1 &

isavailable nm-applet && nm-applet &
isavailable xautolock && xautolock -time 10 -locker ~/.bin/lock.sh &
isavailable dunst && dunst -config ~/.config/dunst/dunstrc &
isavailable xss-lock && xss-lock -- ~/.bin/lock.sh &
isavailable picom && picom --config ~/.config/picom.conf &
isavailable rescuetime && rescuetime &
isavailable unclutter && unclutter &
