#!/usr/bin/env zsh

. $HOME/.xinitrc
. $HOME/.env-secrets

export vblank_mode=1

if [ -f /usr/bin/qtile ]; then
        exec dbus-launch --auto-syntax --exit-with-session /usr/bin/qtile start
elif [ -f /usr/bin/i3 ]; then
        exec i3
elif [ -f /usr/local/bin/dwm ]; then
	. $HOME/.bin/startdwm
fi
