#!/usr/bin/env zsh

# Test if $1 is available
isavailable() {
    type "$1" &>/dev/null
}

# screen powersave
xset +dpms
xset dpms 0 0 900
xset r rate 180 40

# 230 has IPS or TN screen with 125.37 DPI
xrandr --dpi 125.37

# run xrdb
[[ -f $HOME/.Xresources ]] && xrdb -load $HOME/.Xresources

isavailable picom && picom --config ~/.config/picom.conf &
isavailable nm-applet && nm-applet &
isavailable xautolock && xautolock -time 10 -locker ~/.bin/lock &
isavailable dunst && dunst -config ~/.config/dunst/dunstrc &
isavailable xss-lock && xss-lock -- ~/.bin/lock &
isavailable unclutter && unclutter &
isavailable blueman-applet && blueman-applet &
isavailable setxkbmap && setxkbmap -option caps:escape &
isavailable xbindkeys && xbindkeys &
isavailable conky && conky --daemonize &
isavailable 1password && 1password --silent &

bash $HOME/.bin/lightsOn.sh &
