---
- hosts: localhost
  pre_tasks:
    - pause:
        prompt: "App Store email (mas)"
      when: (lookup('env', 'CI') == '') and (ansible_distribution_major_version < '11')
      register: "mas_email"
    - pause:
        prompt: "App store password (mas)"
      when: (lookup('env', 'CI') == '') and (ansible_distribution_major_version < '11')
      register: "mas_password"
  roles:
    - role: geerlingguy.homebrew
      tags: [deps, homebrew, osx]
      vars:
        - homebrew_use_brewfile: yes
        - homebrew_brewfile_dir: "./roles/osx/tasks/"

    - role: osx
      tags: [osx]
    - role: common
      tags: [common, dotfiles, osx]
    - role: markosamuli.pyenv
      tags: [deps, python, osx]
      vars:
        - pyenv_python3_version: "3.9.0b5"
        - pyenv_python_versions:
            - "{{ pyenv_python3_version }}"
        - pyenv_global: "{{ pyenv_python3_version }} system"
        - pyenv_virtualenvwrapper: true
        - pyenv_detect_existing_install: true
        - pyenv_init_shell: false
        - pyenv_install_from_package_manager: false
