#!/usr/bin/env bash
if [ ! -d "$HOME/mail" ]; then
    mkdir -p $HOME/{work,personal}
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    mbsync=/usr/bin/mbsync
    mu=/usr/bin/mu
elif [[ "$OSTYPE" == "darwin"* ]]; then
    mbsync=/usr/local/bin/mbsync
    mu=/usr/local/bin/mu
fi

echo "Syncing mailboxes with '$mbsync'"
$mbsync -Va

echo "Indexing emails with '$mu'"
$mu index

