#!/bin/zsh

tme() {
    echo -e "$(date +'%H:%M:%S')"
}

dte() {
    echo -e "$(date +'%d %b %y')"
}

vpn() {
    output="$(nordvpn status | grep Connected)"
    if [[ -n $output ]] then
       country="$(nordvpn status \
           | grep Country \
           | sed s/'Country: '// \
           | tr '[:upper:]' '[:lower:]')"

       echo -e "vpn/c @ $country"
    else
        echo -e "vpn/n"
    fi
}

bat() {
    bash $HOME/.bin/battery-stats
}

volume() {
    bash $HOME/.bin/volume-stats
}

while true; do
    xsetroot -name "旅 $(vpn) |  $(tme)  $(dte) | $(bat) | $(volume)"
    sleep 1m
done &
