#!/usr/bin/env python
#
# Copyright (c) 2015, Ben Mezger, me@benmezger.nl
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

from urllib2 import urlopen
from json import loads
from socket import gethostbyname, gethostname
from os import getenv

# returns {u'X-Real-Ip': [u'xx.xx.xx.xx'], u'X-Ifconfig-Country': [u'xxx'], u'X-Ifconfig-Ip':
# [u'xx.xx.xx.xx'], u'Accept-Encoding': [u'xxx'], u'User-Agent': [u'xxx']}
ip_info = loads(urlopen("https://ifconfig.co/json").read())

real_ip = ip_info.get('ip')
country = ip_info.get('country')
city  = ip_info.get("city")

is_torified = loads(urlopen("https://check.torproject.org/api/ip").read()).get("IsTor")

local_ip = gethostbyname(gethostname())
hostname = gethostname()

print "Public IP:", real_ip
print "Country:", country
print "City", city

print
print "Is Torified:", "Yes" if is_torified == True else "No"
print

print "Local IP:", local_ip
print "Hostname:", hostname

http_proxy = getenv("http_proxy")
https_proxy = getenv("https_proxy")
ftp_proxy = getenv("ftp_proxy")

print "\nLocal variables:"
print "HTTP Proxy:", http_proxy if True else "None"
print "HTTPS Proxy:", https_proxy if True else "None"
print "FTP Proxy:", ftp_proxy if True else "None"
