#!/usr/bin/env zsh

# default to vim
export EDITOR=vim

# default to linux
bin=/usr/bin

if [[ "$OSTYPE" == "darwin"* ]]; then
        bin=/usr/local/bin
fi

if [[ -x "$(command -v nvim)" ]]; then
        export EDITOR=$bin/nvim
fi

if [[ -x "$(command -v emacs)" ]]; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
                is_running="$(pgrep -x Emacs)"
        else
                is_running="$(pgrep -x emacs)"
        fi

        export EDITOR='$bin/emacsclient -c -a ""'
        if [[ ! $is_running ]]; then
                echo "Starting emacs daemon.."
                $bin/emacs --daemon 2>/dev/null
        fi
fi

echo "Running editor '$EDITOR'"
eval $EDITOR '$@'
