#!/bin/zsh

tme() {
    echo -e "$(date +'%H:%M')"
}

dte() {
    echo -e "$(date +'%a %d %b %y')"
}

vpn() {
    output="$(nordvpn status | grep Connected)"
    if [[ -n $output ]] then
       country="$(nordvpn status \
           | grep Country \
           | sed s/'Country: '// \
           | tr '[:upper:]' '[:lower:]')"

       echo -e "vpn/c @ $country"
    else
        echo -e "vpn/n"
    fi
}

bat() {
    bash $HOME/.bin/battery-stats
}

volume() {
    bash $HOME/.bin/volume-stats
}

emails() {
    echo -e "mi: $(notmuch count tag:inbox and tag:me)" \
        "u: $(notmuch count tag:unread and tag:me)"
}

xsetroot -name "  $(emails) |  $(vpn) |  $(tme)  $(dte) | $(bat) | $(volume)"
