#!/usr/bin/bash

# Author: Ben Mezger <me@benmezger.nl>
# Created at <2020-10-02 Fri 08:53>

FONT="-fn Hack-10"
THEME="-nb #1e1e1e -sf #1e1e1e -sb #f4800d -nf #F4800d"
LINE_LEN="-l 15"
DMENU_CMD="dmenu $THEME $FONT $LINE_LEN"


function help() {
   echo "Dmenu utitlity."
   echo
   echo "Syntax:      dmenu [launcher|clipboard]"
   echo "options:"
   echo "    launcher     Application launcher"
   echo "    clipboard    Display and select clipboard history (requires greenclip)"
   echo "    switch       Switch between opened window (requires wmctrl)"
   echo "    help         Display this help message"
   echo
}

case "$1" in
    "launcher")
        dmenu_run $FONT $LINE_LEN $THEME
        ;;
    "clipboard")
        greenclip print \
            | sed '/^$/d' \
            | dmenu $FONT $THEME -i $LINE_LEN -p clipboard \
            | xargs -r -d'\n' -I '{}' greenclip print '{}'
        ;;
    "help")
        help
        ;;
    "switch")
        num=$(wmctrl -l \
            | sed 's/  / /' \
            | cut -d " " -f 4- \
            | nl -w 3 -n rn \
            | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' \
            | dmenu -b -i -p "window" $FONT $THEME $LINE_LEN \
            | cut -d '-' -f -1)
        [[ -z "$num" ]] && exit
        wmctrl -l \
            | sed -n "$num p" \
            | cut -c -10 \
            | xargs wmctrl -i -a
        ;;
    *)
        help
        ;;
esac
