#!/bin/bash

HOME_PATH=/home
ROOT_PATH=/
SNAPSHOTS_PATH=/.snapshots
BACKUP_DATE=$(date +"%d.%m.%Y_%H:%M:%S")

if [ ! -d "$SNAPSHOTS_PATH/@root" ]; then
    mkdir $SNAPSHOTS_PATH/@root
fi

if [ ! -d "$SNAPSHOTS_PATH/@home" ]; then
    mkdir $SNAPSHOTS_PATH/@home
fi

sudo btrfs subv snap -r $ROOT_PATH $SNAPSHOTS_PATH/@root/root_$BACKUP_DATE
sudo btrfs subv snap -r $HOME_PATH $SNAPSHOTS_PATH/@home/home_$BACKUP_DATE
