#!/bin/bash

while true; do
    zsh $HOME/.bin/dwmbar
    sleep 1m
done &

python $HOME/.bin/detect-screen

# relaunch DWM if the binary changes, otherwise bail
csum=""
new_csum=$(sha1sum $(which dwm))
while true; do
	if [ "$csum" != "$new_csum" ]; then
		csum=$new_csum
		dwm
	else
	    exit 0
	fi
	new_csum=$(sha1sum $(which dwm))
	sleep 0.5
done
