#!/usr/bin/env zsh

HOMEDIR=$(eval echo ~)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	tmux=/usr/bin/tmux
elif [[ "$OSTYPE" == "darwin"* ]]; then
	tmux=/usr/local/bin/tmux
fi

$tmux has-session -t default &>/dev/null
if [[ $? -eq 1 ]]; then
	$tmux new -s default -d -c $HOMEDIR
	$tmux source-file $HOMEDIR/.tmux.conf
fi
