#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Opening default OSX toolbar apps.."

        open /Applications/Trailer.app
        open /Applications/Clocker.app
        open /Applications/Amphetamine.app
        open /Applications/Bitwarden.app
        open /Applications/Maccy.app
        open /Applications/WhatsApp.app
        open "/Applications/Backup\ and\ Sync.app/"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Not supported atm"
        exit 0
fi
