#!/bin/sh
#
# Log commit messages as a 'highlight' in RescueTime Premium
#
# To enable this hook:
#
# 1. Place this file in your project's .git/hooks directory and make sure its name is "post-commit".
# 2. Make sure it has executable permissions (chmod +x post-commit)
# 3. All commits will be automatically logged as highlight events.
#

API_KEY=$RESCUE_TIME_API_KEY
DIR=`git rev-parse --show-toplevel`
PROJECT=`echo $DIR | rev | cut -d'/' -f 1 | rev`

# REQUIRED FIELDS - Today's date and commit message
MESSAGE=$(git log -1 HEAD --pretty=format:%s)
DATE_TODAY=$(date +"%Y-%m-%d %H:%M:%S")

if [[ ${#MESSAGE} -gt 20 ]]; then
    curl --data "key=$API_KEY&highlight_date=$DATE_TODAY&description=$MESSAGE&source=$PROJECT" https://www.rescuetime.com/anapi/highlights_post
fi
