[".config/base16-shell"]
    type = "archive"
    url = "https://github.com/chriskempson/base16-shell/archive/refs/heads/master.zip"
    stripComponents = 1

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
    stripComponents = 1

[".bin/notmuch-extract-patch"]
    type = "file"
    url = "https://raw.githubusercontent.com/aaptel/notmuch-extract-patch/master/notmuch-extract-patch"

[".bin/rofi-power"]
    type = "file"
    executable = true
    url = "https://raw.githubusercontent.com/jluttine/rofi-power-menu/master/rofi-power-menu"

[".zsh/fzf-theme.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/fnune/base16-fzf/master/bash/base16-gruvbox-dark-hard.config"

[".bin/speedtest.py"]
    type = "file"
    executable = true
    url = "https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py"

{{- if eq .chezmoi.os "linux" }}
[".bin/i3-autodisplay"]
    type = "file"
    executable = true
    url = "https://github.com/lpicanco/i3-autodisplay/releases/download/v0.6/i3-autodisplay-0.6-linux-amd64"
{{- end }}

[".antidote"]
    type = "git-repo"
    refreshPeriod = "168h"
    url = "https://github.com/mattmc3/antidote.git"
