#!/bin/env python

import readline, rlcompleter
import os
import atexit


### Indenting
class TabCompleter(rlcompleter.Completer):
    """Completer that supports indenting"""

    def complete(self, text, state):
        if not text:
            return ("    ", None)[state]
        else:
            return rlcompleter.Completer.complete(self, text, state)


readline.set_completer(TabCompleter().complete)

### Add autocompletion
if "libedit" in readline.__doc__:
    readline.parse_and_bind("bind -e")
    readline.parse_and_bind("bind '\t' rl_complete")
else:
    readline.parse_and_bind("tab: complete")

### Add history
histfile = os.path.join(os.environ["HOME"], ".pyhist")
try:
    readline.read_history_file(histfile)
except IOError:
    pass

atexit.register(readline.write_history_file, histfile)
del histfile
