#!/usr/bin/env zsh

if [[ "$ZPROF" = true ]]; then
        zmodload zsh/zprof
fi

source $HOME/.zsh/init.zsh
source $HOME/.zsh/exports.zsh

source $HOME/.antidote/antidote.zsh
# Set the root name of the plugins files (.txt and .zsh) antidote will use.
zsh_plugins=$HOME/.zsh/plugins

# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Lazy-load antidote from its functions directory.
fpath=(/path/to/antidote/functions $fpath)
autoload -Uz antidote

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh

source $HOME/.zsh/evals.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/stack.zsh
source $HOME/.zsh/keys.zsh
source $HOME/.zsh/aliases.zsh

# load base16 themes if on terminal
if [[ -n $DISPLAY ]]; then
        # base16 theme
        base16_gruvbox-dark-hard
fi

if [[ "$ZPROF" = true ]]; then
        exit_hook() {
                print "zprof for process $$"
                zprof

                while read input; do
                done

                exit 0
        }
        add-zsh-hook zshexit exit_hook
fi

# emacs(tramp): disable zsh line editor because zsh uses
# left-hand side and right-hand side prompts in parallel
# see: TRAMP does not connect to the remote host at
# https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html
if [[ $TERM == "dumb" ]]; then
        unsetopt zle && PS1='$ ' && return
fi

# initialize completion
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
        compinit
else
        compinit -C
fi

# enable approximate matches for completion
zstyle ':completion:*' completer _expand _complete _approximate

# Apply theme
base16_gruvbox-dark-hard
