#!/usr/bin/env zsh

if [[ "$ZPROF" = true ]]; then
        zmodload zsh/zprof
fi

# emacs(tramp): disable zsh line editor because zsh uses
# left-hand side and right-hand side prompts in parallel
# see: TRAMP does not connect to the remote host at
# https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html
if [[ $TERM == "dumb" ]]; then
        unsetopt zle && PS1='$ ' && return
fi

source $HOME/.zsh/init.zsh
source $HOME/.zsh/exports.zsh

source $HOME/.antidote/antidote.zsh
# Set the root name of the plugins files (.txt and .zsh) antidote will use.
zsh_plugins=$HOME/.zsh/plugins

# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh

source $HOME/.zsh/evals.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/stack.zsh
source $HOME/.zsh/keys.zsh
source $HOME/.zsh/aliases.zsh

# load base16 themes if on terminal
if [[ -n $DISPLAY ]]; then
        # base16 theme
        base16_gruvbox-dark-hard
fi

if [[ "$ZPROF" = true ]]; then
        exit_hook() {
                print "zprof for process $$"
                zprof

                while read input; do
                done

                exit 0
        }
        add-zsh-hook zshexit exit_hook
fi

# initialize completion
# zsh-defer defers compinit until after the first prompt, removing it from
# startup time. Run full compinit if the dump is >24h old OR if any completion
# file in fpath is newer than the dump (e.g. after installing system packages).
_compinit_maybe_refresh() {
  setopt local_options extendedglob
  local dump=~/.zcompdump
  local newest_completion=()
  [[ -d $ZSH_SITE_FUNCTIONS ]] && newest_completion=($ZSH_SITE_FUNCTIONS/*(#qN.Om[1]))
  if [[ -n ${dump}(#qN.mh+168) ]] || \
     [[ -n $newest_completion && $newest_completion -nt $dump ]]; then
    compinit -d $dump
  else
    compinit -C -d $dump
  fi
}
zsh-defer _compinit_maybe_refresh

# enable approximate matches for completion
zstyle ':completion:*' completer _expand _complete _approximate
