#!/usr/bin/env zsh

. $HOME/.xinitrc
. $HOME/.env-secrets

# default wm
WM=$(which i3)

if [ -n "$WM" ] && [ -x "$WM" ]; then
        exec "$WM"
elif which qtile >/dev/null 2>&1; then
        exec /usr/bin/qtile start
elif which dwm >/dev/null 2>&1; then
        . $HOME/.bin/startdwm
fi
