---
- name: Enable pcscd service
  become: yes
  systemd:
    name: pcscd.socket
    enabled: yes
  tags:
    - services

- name: Create user systemd directory
  file:
    path: ~/.config/systemd/user
    state: directory
    mode: "0755"
  tags:
    - services

- name: Install Greenclip service
  template:
    src: services/greenclip.service
    dest: ~/.config/systemd/user/greenclip.service
  tags:
    - services
    - deps

- name: Enable Greenclip service
  systemd:
    scope: user
    name: greenclip.service
    enabled: yes
  tags:
    - services
    - deps

- name: Install MBSync service
  template:
    src: services/mbsync.service
    dest: ~/.config/systemd/user/mbsync.service
  tags:
    - services
    - deps

- name: Install MBSync timer service
  template:
    src: services/mbsync.timer
    dest: ~/.config/systemd/user/mbsync.timer
  tags:
    - services
    - deps

- name: Enable MBSync timer service
  systemd:
    scope: user
    name: mbsync.timer
    enabled: yes
  tags:
    - services
    - deps
