# from: https://github.com/lpicanco/i3-autodisplay
displays:
  - name: HDMI-1
    workspaces: [1]
    randr_extra_options: "--primary --pos 2160x1377 --rotate normal"
  - name: HDMI-0
    workspaces: [11]
    randr_extra_options: "--pos 0x0 --rotate right"
