# from: https://github.com/lpicanco/i3-autodisplay
displays:
  - name: HDMI-1 # bottom
    workspaces: [1]
    randr_extra_options: "--primary --rotate normal --pos 0x2160"
  - name: HDMI-0 # top
    workspaces: [11]
    randr_extra_options: "--pos 0x0 --rotate normal"
