---
- name: Clone Aura
  git: repo=https://aur.archlinux.org/aura-bin.git dest=/tmp/aura-bin force=yes

- name: Build and install Aura
  command: chdir=/tmp/aura-bin makepkg -si --noconfirm

- include: pacman.yml
- include: python.yml
