---
- name: Install Pacman packages
  become: true
  command: pacman -S {{ item }} --noconfirm
  with_items:
    - python2
    - python2-pip
    - vim
    - fasd
    - ack
    - gnupg2
    - tmux
    - tor
    - valgrind
    - firefox
    - chromium
    - zsh
    - xorg-xset
    - xorg-xrdb
    - dunst
    - pcsclite
    - feh
    - pcsc-tools

- name: Install packages from AUR
  command: aura -A {{ item }} --noconfirm
  become: true
  with_items:
    - wire-desktop-bin
    - xss-lock
    - spotify
    - ttf-font-awesome
    - numix-icon-theme-git
    - gitter
    - dropbox
    - git-crypt
    - solaar

