#!/usr/bin/env bash

# Author: Ben Mezger <me@benmezger.nl>
# Created at <2020-10-02 Fri 08:53>

FONT="-fn Hack-10"
THEME=""
LINE_LEN="-l 15"
DMENU_CMD="dmenu $THEME $FONT $LINE_LEN"
SCRIPT=`realpath -s $0`

export PATH="$PATH:$HOME/.bin:/opt/riscv/bin/:/opt/xilinx/Vivado/2021.2/bin"

function help() {
   echo "Dmenu utitlity."
   echo
   echo "Syntax:      dmenu [launcher|clipboard]"
   echo "options:"
   echo "    launcher     Application launcher"
   echo "    clipboard    Display and select clipboard history (requires greenclip)"
   echo "    switch       Switch between opened window (requires wmctrl)"
   echo "    calculate    Calculator (requires calc)"
   echo "    locate       Locate and open files (requires mlocate and xdg-open)"
   echo "    help         Display this help message"
   echo
}

case "$1" in
    "launcher")
        dmenu_run $FONT $LINE_LEN $THEME
        ;;
    "clipboard")
        greenclip print \
            | sed '/^$/d' \
            | $DMENU_CMD -i -p clipboard \
            | xargs -r -d'\n' -I '{}' greenclip print '{}'
        ;;
    "help")
        help
        ;;
    "switch")
        num=$(wmctrl -l \
            | sed 's/  / /' \
            | cut -d " " -f 4- \
            | nl -w 3 -n rn \
            | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' \
            | $DMENU_CMD -b -i -p "window" \
            | cut -d '-' -f -1)
        [[ -z "$num" ]] && exit
        wmctrl -l \
            | sed -n "$num p" \
            | cut -c -10 \
            | xargs wmctrl -i -a
        ;;
    "calculate")
        while inp=$(echo -e "$oup" | $DMENU_CMD -p Calculate: $THEME $FONT)
        do
            if oup2=$(calc -pd "$inp"); then
                echo -n "$oup2" | xsel -i
                oup="$oup2\n$oup"
            fi
        done
        ;;
    "locate")
        input="$(xsel -o | $DMENU_CMD -p "file search":)"
        if [[ "$input" != '' ]]; then
            result="$(echo "$input" \
                | locate -e -r "$input" \
                | $DMENU_CMD -p "search result:" )"
            xdg-open $result
        fi
        ;;
    *)
        input=`echo -en "launcher\nclipboard\nswitch\ncalculate\nlocate" | $DMENU_CMD -p "cmd"`
        if [[ "$input" != '' ]]; then
            exec $SCRIPT $input
        else
            help
        fi
        ;;
esac
