#!/usr/bin/env zsh

if [[ -v CUSTOM_EDITOR ]]; then
        eval $CUSTOM_EDITOR '$@'
        exit $?
fi

# default to vim
export EDITOR=vim

# default to linux
bin=/usr/bin

if [[ "$OSTYPE" == "darwin"* ]]; then
        bin=$(brew --prefix)/bin
fi

if [[ -x "$(command -v nvim)" ]]; then
        export EDITOR=$bin/nvim
fi

if [[ -x "$(command -v emacs)" ]]; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
                is_running="$(pgrep -x Emacs)"
        else
                is_running="$(pgrep -x emacs)"
        fi

        export EDITOR='$bin/emacsclient -q -c -a ""'
        if [[ ! $is_running ]]; then
                echo "Starting emacs daemon.."
                $bin/emacs --daemon 2>/dev/null
        fi
fi

eval $EDITOR '$@'
