#!/usr/bin/env zsh

if [[ ${OSTYPE} == darwin* ]]; then
    echo "Updating OSX packages"
    brew update && brew upgrade && brew cleanup
elif [[ -f /etc/arch-release ]]; then
    echo "Updating Arch Linux packages"
    pacman -Syyu --noconfirm
fi

echo "Updating Emacs packages"
emacs --batch \
    --load $HOME/.emacs.d/early-init.el \
    --load $HOME/.emacs.d/init.el \
    --eval "(straight-pull-all)" \
    --eval "(straight-freeze-versions)"

cp -rf $HOME/.emacs.d/straight/versions/default.el \
    $(chezmoi source-path)/dot_emacs.d/straight/versions/default.el

echo "Updating ZSH"
zsh $HOME/.antidote/antidote update

echo "Updating Tmux"
"$HOME"/.tmux/plugins/tpm/bin/update_plugins all
