#!/usr/bin/env python
#
# Copyright (c) 2015, Ben Mezger, me@benmezger.nl
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

import socket
from urllib.request import urlopen
from json import loads
from os import getenv


def main() -> None:
    ip_info = _fetch_url("https://ipwho.is/")

    print("Public IP:", ip_info.get("ip"))
    print("Country:", ip_info.get("country"))
    print("City:", ip_info.get("city"))

    print("Local IP:", _get_local_ip())
    print("Hostname:", socket.gethostname())
    print("ISP:", ip_info.get("connection", {}).get("isp", None))

    print("\nLocal variables:")
    print("HTTP Proxy:", getenv("http_proxy"))
    print("HTTPS Proxy:", getenv("https_proxy"))
    print("FTP Proxy:", getenv("ftp_proxy"))


def _get_local_ip() -> str:
    # safer way to getting the local IP
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))

    local_ip = s.getsockname()[0]

    s.close()
    return local_ip


def _fetch_url(url: str) -> dict:
    return loads(urlopen(url).read())


if __name__ == "__main__":
    main()
