#!/usr/bin/env zsh

if [[ ${OSTYPE} == darwin* ]]; then
    echo "Updating OSX packages"
    brew update && brew upgrade && brew cleanup
elif [[ -f /etc/arch-release ]]; then
    echo "Updating Arch Linux packages"
    sudo pacman -Syyu --noconfirm
fi

echo "Updating Emacs packages"
emacs --batch \
    --load $HOME/.emacs.d/early-init.el \
    --load $HOME/.emacs.d/init.el \
    --eval "(straight-pull-all)" \
    --eval "(straight-rebuild-all)" \
    --eval "(straight-freeze-versions)"

echo "Native-compiling Emacs packages"
emacs --batch \
    --eval "(when (fboundp 'native-compile-async)
              (native-compile-async
                (list (expand-file-name \"straight/build\" user-emacs-directory))
                'recursively)
              (while (or comp-files-queue
                         (and (fboundp 'comp-async-runnings)
                              (> (comp-async-runnings) 0)))
                (sleep-for 1)))"

cp -rf $HOME/.emacs.d/straight/versions/default.el \
    $(chezmoi source-path)/dot_emacs.d/straight/versions/default.el

echo "Refreshing Emacs env file"
$HOME/.bin/emacs-refresh-env

echo "Updating ZSH"
zsh $HOME/.antidote/antidote update

echo "Updating Tmux"
"$HOME"/.tmux/plugins/tpm/bin/update_plugins all
