#!/usr/bin/env zsh

if [[ ${OSTYPE} == darwin* ]]; then
    echo "Updating OSX packages"
    brew update && brew upgrade && brew cleanup
fi

echo "Updating Emacs Doom"
doom sync -e -u --force

echo "Updating ZSH"
antidote update

echo "Updating Tmux"
"$HOME"/.tmux/plugins/tpm/bin/update_plugins all
