# This is a default home.nix generated by the follwing hone-manager command
# 
# home-manager init ./

{ config, lib, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "${config.username}";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.05"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = [
    pkgs.git
    pkgs.chezmoi
    pkgs.google-chrome
    pkgs.emacs
    pkgs.ledger
    pkgs.hugo
    pkgs.notmuch
    pkgs.isync
    pkgs.zsh
    pkgs.rclone
    pkgs.discord
    pkgs.delta # git-delta
    pkgs.fzf
    pkgs.gnuplot
    pkgs.picom
    pkgs.gist
    pkgs.unclutter
    pkgs.wakatime
    pkgs.tmux
    pkgs.sxhkd
    pkgs.scrot
    pkgs.alacritty
    pkgs.fd
    pkgs.arandr
    pkgs.diff-so-fancy
    pkgs.dmenu
    pkgs.docker
    pkgs.docker-compose
    pkgs.dunst
    pkgs.eza
    pkgs.fasd
    pkgs.feh
    pkgs.httpie
    pkgs.imagemagick
    pkgs.ispell
    pkgs.rofi
    pkgs.calc
    pkgs.discord
    pkgs.xclip
    pkgs.redshift
    pkgs.htop
    pkgs.geoclue2
    pkgs.rofi-calc
    pkgs.rofi-emoji
    pkgs.conky
    pkgs.xdg-user-dirs
    pkgs.antidote
    pkgs.pyenv
    pkgs.lua
    pkgs.python311
    pkgs.xdotool
    pkgs.wmctrl
    pkgs.poetry
    pkgs.xbindkeys
    pkgs.networkmanagerapplet
    pkgs.xautolock
    pkgs.xss-lock
    pkgs.blueman
    pkgs.xorg.setxkbmap
    pkgs.pciutils
    pkgs.pavucontrol

    # Adds the 'hello' command to your environment. It prints a friendly
    # # "Hello, world!" when run.
    # pkgs.hello

    # # It is sometimes useful to fine-tune packages, for example, by applying
    # # overrides. You can do that directly here, just don't forget the
    # # parentheses. Maybe you want to install Nerd Fonts with a limited number of
    # # fonts?
    # (pkgs.nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })

    # # You can also create simple shell scripts directly inside your
    # # configuration. For example, this adds a command 'my-hello' to your
    # # environment:
    # (pkgs.writeShellScriptBin "my-hello" ''
    #   echo "Hello, ${config.home.username}!"
    # '')
  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. If you don't want to manage your shell through Home
  # Manager then you have to manually source 'hm-session-vars.sh' located at
  # either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/m3tam3re/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    # EDITOR = "emacs";
  };

  home.activation.createDirs = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p $HOME/workspace
    mkdir -p $HOME/documents
    mkdir -p $HOME/downloads
  '';

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
  programs.zsh.antidote.enable = true;
}
