---
- name: Install Gitmux
  poll: 0
  async: 45
  register: gitmux_result
  shell: go get -u github.com/arl/gitmux
  environment:
    - GOPATH: "{{ ansible_env.HOME }}/workspace/go"
  args:
    warn: no
  tags:
    - remote
    - go

- name: Install Go LSP
  poll: 0
  async: 45
  register: golsp_result
  shell: go get -u golang.org/x/tools/gopls
  environment:
    - GOPATH: "{{ ansible_env.HOME }}/workspace/go"
  args:
    warn: no
  tags:
    - remote
    - go

- name: Install Git Changelog generator
  poll: 0
  async: 45
  register: ghlog_result
  shell: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  environment:
    - GO111MODULE: "on"
    - GOPATH: "{{ ansible_env.HOME }}/workspace/go"
  args:
    warn: no
  tags:
    - remote
    - go

- name: Wait for async tasks
  tags:
    - remote
    - go
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: result
  until: result.finished
  delay: 10
  retries: 10
  with_items:
    - "{{ gitmux_result }}"
    - "{{ golsp_result }}"
    - "{{ ghlog_result }}"
