---
- name: Increase window resize speed for Cocoa applications
  osx_defaults:
      domain: NSGlobalDomain
      key: NSWindowResizeTime
      type: float
      value: 0.001
      state: present

- name: Save to disk (not to iCloud) by default
  osx_defaults:
      domain: NSGlobalDomain
      key: NSDocumentSaveNewDocumentsToCloud
      type: bool
      value: false
      state: present

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
      domain: com.apple.LaunchServices
      key: LSQuarantine
      type: bool
      value: false
      state: present

- name: Disable automatic capitalization as it’s annoying when typing code
  osx_defaults:
      domain: NSGlobalDomain
      key: NSAutomaticCapitalizationEnabled
      type: bool
      value: false
      state: present

- name: Disable smart dashes as they’re annoying when typing code
  osx_defaults:
      domain: NSGlobalDomain
      key: NSAutomaticDashSubstitutionEnabled
      type: bool
      value: false
      state: present

- name: Disable automatic period substitution as it’s annoying when typing code
  osx_defaults:
      domain: NSGlobalDomain
      key: NSAutomaticPeriodSubstitutionEnabled
      type: bool
      value: false
      state: present

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults:
      domain: NSGlobalDomain
      key: NSAutomaticQuoteSubstitutionEnabled
      type: bool
      value: false
      state: present

- name: Disable auto-correct
  osx_defaults:
      domain: NSGlobalDomain
      key: NSAutomaticSpellingCorrectionEnabled
      type: bool
      value: false
      state: present

- name: Enable tap to click for this user and for the login screen
  osx_defaults:
      domain: NSGlobalDomain
      key: com.apple.mouse.tapBehavior
      type: int
      value: 1
      state: present
  osx_defaults:
      domain: NSGlobalDomain
      key: com.apple.mouse.tapBehavior
      type: int
      value: 1
      state: present


- name: Increase sound quality for Bluetooth headphones/headsets
  osx_defaults:
      domain: com.apple.BluetoothAudioAgent
      key: "Apple Bitpool Min (editable)"
      type: int
      value: 40
      state: present

- name: Set a fast keyboard repeat rate
  osx_defaults:
      domain: NSGlobalDomain
      key: KeyRepeat
      type: int
      value: 1
      state: present
  osx_defaults:
      domain: NSGlobalDomain
      key: InitialKeyRepeat
      type: int
      value: 10
      state: present

- name: Finder -  show hidden files by default
  osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: true
      state: present

- name: When performing a search, search the current folder by default
  osx_defaults:
      domain: com.apple.finder
      key: FXDefaultSearchScope
      type: string
      value: SCcf
      state: present

- name: Disable the warning when changing a file extension
  osx_defaults:
      domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      type: bool
      value: false
      state: present

- name: Avoid creating .DS_Store files on network or USB volumes
  osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteNetworkStores
      type: bool
      value: true
      state: present
  osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteUSBStores
      type: bool
      value: true
      state: present

- name: Disable disk image verification
  osx_defaults:
      domain: com.apple.frameworks.diskimages
      key: skip-verify
      type: bool
      value: true
      state: present
  osx_defaults:
      domain: com.apple.frameworks.diskimages
      key: skip-verify-locked
      type: bool
      value: true
      state: present
  osx_defaults:
      domain: com.apple.frameworks.diskimages
      key: skip-verify-remote
      type: bool
      value: true
      state: present

- name: Use list view in all Finder windows by default
  osx_defaults:
      domain: com.apple.finder
      key: FXPreferredViewStyle
      type: string
      value: Nlsv
      state: present

- name: Disable the warning before emptying the Trash
  osx_defaults:
      domain: com.apple.finder
      key: WarnOnEmptyTrash
      type: bool
      value: false
      state: present

- name: Speed up Mission Control animations
  osx_defaults:
      domain: com.apple.dock
      key: expose-animation-duration
      type: float
      value: 0.1
      state: present
