---
- name: Login to Apple Store
  command: mas signin "{{ mas_email }}" "{{ mas_password }}"
  when: ansible_distribution_major_version < '11'

- name: Install Apple Store apps using mas
  poll: 0
  async: 45
  command: mas install "{{ item }}"
  with_items:
    - 1094298678 # RealDNS
    - 443126292  # TrashMe
    - 737047715  # Magic Number
    - 1262957439 # Textual 7
    - 639764244  # Xee
    - 1054607607 # Helium
    - 937984704  # Amphetamine
